<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\Category;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = Category::all();

        $products = [
            // Anéis
            [
                'category_id' => $categories->where('slug', 'aneis')->first()->id,
                'name' => 'Anel de Compromisso Diamante',
                'slug' => 'anel-compromisso-diamante',
                'type' => 'Anel de Noivado',
                'material' => 'Ouro Branco 18k',
                'sku' => 'A-001',
                'description' => 'Anel de compromisso com diamante central de 1.5ct, corte brilhante, em ouro 18k branco. Acompanha certificado de autenticidade.',
                'price' => 8500.00,
                'stock' => 5,
                'available_sizes' => ['10', '12', '14'],
                'available_colors' => ['Ouro Branco', 'Ouro Amarelo'],
                'customization_options' => ['Gravação interna', 'Ajuste personalizado', 'Embalagem para presente'],
                'image' => 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop',
                'is_active' => true,
            ],
            [
                'category_id' => $categories->where('slug', 'aneis')->first()->id,
                'name' => 'Aliança Ouro 18k',
                'slug' => 'alianca-ouro-18k',
                'type' => 'Aliança',
                'material' => 'Ouro Amarelo 18k',
                'sku' => 'A-002',
                'description' => 'Aliança clássica em ouro 18k amarelo, design elegante e atemporal. Largura de 4mm.',
                'price' => 1200.00,
                'stock' => 15,
                'available_sizes' => ['10', '12', '14', '16'],
                'available_colors' => ['Ouro Amarelo', 'Ouro Branco'],
                'customization_options' => ['Gravação externa', 'Acabamento fosco', 'Ajuste gradual'],
                'image' => 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop',
                'is_active' => true,
            ],
            [
                'category_id' => $categories->where('slug', 'aneis')->first()->id,
                'name' => 'Anel Solitário Rubi',
                'slug' => 'anel-solitario-rubi',
                'type' => 'Anel Solitário',
                'material' => 'Ouro Rosa 18k',
                'sku' => 'A-003',
                'description' => 'Anel solitário com rubi natural de 2ct, engastado em ouro rosa 18k. Peça única e sofisticada.',
                'price' => 3200.00,
                'stock' => 3,
                'available_sizes' => ['10', '12', '14'],
                'available_colors' => ['Ouro Rosa'],
                'customization_options' => ['Ajuste de altura da pedra', 'Embalagem personalizada', 'Certificado de autenticidade'],
                'image' => 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400&h=400&fit=crop',
                'is_active' => true,
            ],

            // Brincos
            [
                'category_id' => $categories->where('slug', 'brincos')->first()->id,
                'name' => 'Brincos Argola Ouro',
                'slug' => 'brincos-argola-ouro',
                'type' => 'Argola',
                'material' => 'Ouro 18k',
                'sku' => 'B-001',
                'description' => 'Brincos argola em ouro 18k amarelo, design minimalista e elegante. Diâmetro de 15mm.',
                'price' => 450.00,
                'stock' => 20,
                'available_sizes' => ['P', 'M'],
                'available_colors' => ['Ouro Amarelo', 'Ouro Branco'],
                'customization_options' => ['Banho extra brilhante', 'Ajuste de tamanho', 'Caixa presente'],
                'image' => 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400&h=400&fit=crop',
                'is_active' => true,
            ],
            [
                'category_id' => $categories->where('slug', 'brincos')->first()->id,
                'name' => 'Brincos Pérola',
                'slug' => 'brincos-perola',
                'type' => 'Brincos de Pérola',
                'material' => 'Prata 925',
                'sku' => 'B-002',
                'description' => 'Brincos com pérolas naturais cultivadas, engastadas em prata 925. Conjunto de 2 unidades.',
                'price' => 280.00,
                'stock' => 12,
                'available_sizes' => ['Único'],
                'available_colors' => ['Prata'],
                'customization_options' => ['Ajuste de comprimento', 'Opcional de banho em ouro'],
                'image' => 'https://images.unsplash.com/photo-1515603406781-cda1174fb369?w=400&h=400&fit=crop',
                'is_active' => true,
            ],
            [
                'category_id' => $categories->where('slug', 'brincos')->first()->id,
                'name' => 'Brincos Zircônia',
                'slug' => 'brincos-zirconia',
                'type' => 'Brincos de Brilho',
                'material' => 'Prata Folheada',
                'sku' => 'B-003',
                'description' => 'Brincos com zircônias cúbicas, brilho intenso similar ao diamante. Em prata folheada a ouro.',
                'price' => 180.00,
                'stock' => 25,
                'available_sizes' => ['Único'],
                'available_colors' => ['Ouro', 'Prata'],
                'customization_options' => ['Caixa premium', 'Ajuste de pressão'],
                'image' => 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400&h=400&fit=crop',
                'is_active' => true,
            ],

            // Colares
            [
                'category_id' => $categories->where('slug', 'colares')->first()->id,
                'name' => 'Colar Corrente Delgada',
                'slug' => 'colar-corrente-delgada',
                'type' => 'Colar Corrente',
                'material' => 'Ouro 18k',
                'sku' => 'C-001',
                'description' => 'Colar corrente delicada em ouro 18k amarelo, comprimento ajustável de 40-45cm.',
                'price' => 380.00,
                'stock' => 18,
                'available_sizes' => ['40cm', '45cm'],
                'available_colors' => ['Ouro Amarelo', 'Ouro Branco'],
                'customization_options' => ['Ajuste de comprimento', 'Pingente personalizado', 'Embalagem de presente'],
                'image' => 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=400&h=400&fit=crop',
                'is_active' => true,
            ],
            [
                'category_id' => $categories->where('slug', 'colares')->first()->id,
                'name' => 'Colar Pingente Coração',
                'slug' => 'colar-pingente-coracao',
                'type' => 'Colar com Pingente',
                'material' => 'Ouro 18k',
                'sku' => 'C-002',
                'description' => 'Colar com pingente coração em ouro 18k, cravejado com pequenos brilhantes. Comprimento 45cm.',
                'price' => 520.00,
                'stock' => 10,
                'available_sizes' => ['45cm'],
                'available_colors' => ['Ouro Amarelo', 'Ouro Branco'],
                'customization_options' => ['Gravação de nome', 'Ajuste de corrente'],
                'image' => 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400&h=400&fit=crop',
                'is_active' => true,
            ],
            [
                'category_id' => $categories->where('slug', 'colares')->first()->id,
                'name' => 'Colar Esmeralda',
                'slug' => 'colar-esmeralda',
                'type' => 'Colar de Pedra',
                'material' => 'Ouro Branco 18k',
                'sku' => 'C-003',
                'description' => 'Colar com esmeralda colombiana de 3ct, engastada em ouro branco 18k. Peça sofisticada.',
                'price' => 4500.00,
                'stock' => 2,
                'available_sizes' => ['45cm'],
                'available_colors' => ['Ouro Branco'],
                'customization_options' => ['Ajuste de corrente', 'Certificado de origem'],
                'image' => 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400&h=400&fit=crop',
                'is_active' => true,
            ],

            // Pulseiras
            [
                'category_id' => $categories->where('slug', 'pulseiras')->first()->id,
                'name' => 'Pulseira Tennis',
                'slug' => 'pulseira-tennis',
                'type' => 'Pulseira Tennis',
                'material' => 'Ouro Branco 18k',
                'sku' => 'P-001',
                'description' => 'Pulseira tennis com diamantes, total de 5ct em ouro branco 18k. Design esportivo e elegante.',
                'price' => 12500.00,
                'stock' => 3,
                'available_sizes' => ['16cm', '18cm'],
                'available_colors' => ['Ouro Branco'],
                'customization_options' => ['Ajuste de tamanho', 'Embalagem premium'],
                'image' => 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400&h=400&fit=crop',
                'is_active' => true,
            ],
            [
                'category_id' => $categories->where('slug', 'pulseiras')->first()->id,
                'name' => 'Pulseira Corrente',
                'slug' => 'pulseira-corrente',
                'type' => 'Pulseira Corrente',
                'material' => 'Ouro 18k',
                'sku' => 'P-002',
                'description' => 'Pulseira corrente grossa em ouro 18k amarelo, design robusto e masculino.',
                'price' => 890.00,
                'stock' => 8,
                'available_sizes' => ['18cm', '20cm'],
                'available_colors' => ['Ouro Amarelo'],
                'customization_options' => ['Ajuste de medida', 'Detalhe gravado'],
                'image' => 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=400&h=400&fit=crop',
                'is_active' => true,
            ],
            [
                'category_id' => $categories->where('slug', 'pulseiras')->first()->id,
                'name' => 'Pulseira Prata',
                'slug' => 'pulseira-prata',
                'type' => 'Pulseira Casual',
                'material' => 'Prata 925',
                'sku' => 'P-003',
                'description' => 'Pulseira artesanal em prata 925, com detalhes em banho de ouro. Comprimento ajustável.',
                'price' => 150.00,
                'stock' => 30,
                'available_sizes' => ['Único'],
                'available_colors' => ['Prata', 'Ouro Rosé'],
                'customization_options' => ['Ajuste de fecho', 'Caixa de presente'],
                'image' => 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=400&h=400&fit=crop',
                'is_active' => true,
            ],

            // Pingentes
            [
                'category_id' => $categories->where('slug', 'pingentes')->first()->id,
                'name' => 'Pingente Cruz',
                'slug' => 'pingente-cruz',
                'type' => 'Pingente Religioso',
                'material' => 'Ouro 18k',
                'sku' => 'P-004',
                'description' => 'Pingente cruz em ouro 18k, design delicado com detalhes em brilhantes.',
                'price' => 320.00,
                'stock' => 15,
                'available_sizes' => ['Único'],
                'available_colors' => ['Ouro Amarelo', 'Ouro Branco'],
                'customization_options' => ['Gravação de iniciais', 'Corrente opcional'],
                'image' => 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=400&h=400&fit=crop',
                'is_active' => true,
            ],
            [
                'category_id' => $categories->where('slug', 'pingentes')->first()->id,
                'name' => 'Pingente Árvore da Vida',
                'slug' => 'pingente-arvore-vida',
                'type' => 'Pingente Simbólico',
                'material' => 'Prata 925',
                'sku' => 'P-005',
                'description' => 'Pingente árvore da vida em prata 925, símbolo de renovação e crescimento.',
                'price' => 180.00,
                'stock' => 22,
                'available_sizes' => ['Único'],
                'available_colors' => ['Prata'],
                'customization_options' => ['Ajuste de corrente', 'Embalagem temática'],
                'image' => 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400&h=400&fit=crop',
                'is_active' => true,
            ],
            [
                'category_id' => $categories->where('slug', 'pingentes')->first()->id,
                'name' => 'Pingente Inicial Personalizado',
                'slug' => 'pingente-inicial-personalizado',
                'type' => 'Pingente Personalizado',
                'material' => 'Ouro 18k',
                'sku' => 'P-006',
                'description' => 'Pingente com inicial personalizada em ouro 18k, disponível em todas as letras do alfabeto.',
                'price' => 250.00,
                'stock' => 50,
                'available_sizes' => ['Único'],
                'available_colors' => ['Ouro Amarelo', 'Ouro Branco', 'Ouro Rosé'],
                'customization_options' => ['Inicial personalizada', 'Gravação de mensagem', 'Embalagem para presente'],
                'image' => 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=400&h=400&fit=crop',
                'is_active' => true,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
